name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite acionar este workflow manualmente na aba "Actions" do GitHub

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cadastroapi:latest,${{ secrets.DOCKERHUB_USERNAME }}/cadastroapi:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max